# Generated by Django 5.2.5 on 2025-09-17 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=100)),
                ('exercise_name', models.CharField(max_length=100)),
                ('set_number', models.IntegerField()),
                ('metric1_value', models.FloatField()),
                ('metric1_unit', models.CharField(max_length=10)),
                ('metric2_value', models.FloatField()),
                ('metric2_unit', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]