# Generated by Django 5.2.6 on 2025-09-26 04:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(default='Misc', max_length=50)),
                ('metric1_name', models.CharField(default='Weight', max_length=50)),
                ('metric1_units', models.JSONField(default=list)),
                ('metric2_name', models.CharField(default='Reps', max_length=50)),
                ('metric2_units', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('set_number', models.IntegerField()),
                ('metric1_value', models.FloatField()),
                ('metric1_unit', models.CharField(max_length=10)),
                ('metric2_value', models.FloatField()),
                ('metric2_unit', models.CharField(max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='api.workoutsession')),
            ],
        ),
    ]
